# Generated by Django 3.2.18 on 2024-01-31 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CFPapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostA2_C1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A2_C1', models.CharField(choices=[('Degre_1', 'Degré 1 J’ai été sensibilisé en mettant en œuvre la démarche de diagnostic lors de mon année probatoire.'), ('Degre_2', 'Degré 2 Je planifie et organise ma démarche de diagnostic.'), ('Degre_3', 'Degré 3 Je conçois le plan d’action : identification des acteurs clés, choix des outils d’investigations'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité d’accompagner mes pairs sur la structuration et la démarche de diagnostic'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostA2_C2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A2_C2', models.CharField(choices=[('Degre_1', 'Degré 1 Je sélectionne et je fais apparaitre les données de mon territoire ou de mes secteurs d’activités'), ('Degre_2', 'Degré 2 Je contextualise les données à l’échelle de la problématique.'), ('Degre_3', 'Degré 3 J’extraie et j’exploite les données pertinentes afin d’identifier les besoins en compétences.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité d’accompagner un collectif de travail pour produire des analyses concertées.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostA2_C3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A2_C3', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les différents types de note et je connais la structure d’une note ou d’un document d’analyse.'), ('Degre_2', 'Degré 2 Je repère les éléments de mon diagnostic à intégrer dans une note d’opportunité ou une note d’analyse en vue de partager les résultats.'), ('Degre_3', 'Degré 3 J’ai produit un écrit lors de mon année probatoire pour présenter les résultats d’un diagnostic.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité d’accompagner des pairs à la production de notes et de documents d’analyse.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostA3_C1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A3_C1', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais le positionnement de mon organisation dans l’écosystème de la formation professionnelle'), ('Degre_2', 'Degré 2 Je contribue à la politique de ma structure avec mes pairs en comparant mon organisation aux structures similaires'), ('Degre_3', 'Degré 3 Je crée des outils d’analyse (double entrée).'), ('Degre_4', 'Degré 4 Je suis force de propositions, de préconisations et de conseils auprès des décideurs.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostA3_C2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A3_C2', models.CharField(choices=[('Degre_1', 'J’ai connaissance des résultats des audits réalisés et des analyses produites par le réseau.'), ('Degre_2', ' Degré 2 Dans un collectif de travail (exemple : cellule de développement), j’identifie les axes de progrès à prioriser'), ('Degre_3', 'Degré 3 J’opère un diagnostic précis du positionnement de mon organisation et je repère les potentiels de développement à court, moyen et long terme.'), ('Degre_4', 'Degré 4 Je mets en perspective les analyses réalisées au regard et par anticipation de l’évaluation du marché.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostA3_C3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A3_C3', models.CharField(choices=[('Degre_1', 'Degré 1 Je suis présent aux instances de concertation'), ('Degre_2', 'Degré 2 Je prépare et participe aux instances de concertation en apportant des éléments à soumettre au collectif.'), ('Degre_3', 'Degré 3 Je contribue à l’ordre du jour des instances de concertation.'), ('Degre_4', 'Je suis consulté sur des orientations précises par rapport à mon champ d’expertise.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostA4_C1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A4_C1', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais le cahier des charges des commanditaires.'), ('Degre_2', 'Degré 2 Je repère les éléments observables d’une situation.'), ('Degre_3', 'Degré 3 J’exploite les bilans de formation, les relevés de conclusions, les rendez-vous entreprises en capitalisant à l’écrit'), ('Degre_4', 'Degré 4 J’anticipe des situations qui pourraient être sensibles et impactantes pour le développement de ma structure'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostA4_C2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A4_C2', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais des outils de diagnostic en particulier ceux du système qualité de ma structure, du réseau.'), ('Degre_2', 'Degré 2 Je connais la méthode de résolution de problème et j’utilise les outils d’analyse de l’environnement'), ('Degre_3', 'Degré 3 Parmi les hypothèses, j’hiérarchise les solutions en mesurant les effets'), ('Degre_4', 'Degré 4 Je contribue aux travaux sur les orientations académiques du réseau.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostA4_C3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A4_C3', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les outils de communication adaptés au conseil : synthèse, note d’opportunité, rapport, etc.'), ('Degre_2', 'Degré 2 Je choisis les outils de communication adaptés aux décideurs.'), ('Degre_3', 'Degré 3 Je propose à l’écrit ou à l’oral un contenu synthétique pour être lu ou entendu par les décideurs.'), ('Degre_4', 'Degré 4 A la demande du DRAFPIC, je rédige et je présente un rapport circonstancié sur une situation complexe.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostA5_C1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A5_C1', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les différentes instances de mon territoire, leurs rôles et leur fonctionnement.'), ('Degre_2', 'Degré 2 J’analyse le positionnement des acteurs et les enjeux pour chacune des parties prenantes'), ('Degre_3', 'Degré 3 Je suis capable d’adapter ma posture et mon discours en fonction de mes interlocuteurs'), ('Degre_4', 'Degré 4 Je suis sollicité en qualité d’expert de la formation professionnelle tout au long de la vie par le DRAFPIC ou par les acteurs de mon territoire'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostA5_C2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A5_C2', models.CharField(choices=[('Degre_1', 'Degré 1 Je distingue les 3 voies de formation professionnelle. Je m’informe en interne sur les missions, l’offre et les moyens des structures'), ('Degre_2', 'Degré 2 Je connais la carte de la formation professionnelle de l’éducation nationale de mon académie.'), ('Degre_3', 'Degré 3 Je sais argumenter les spécificités et les atouts de mon organisation, à l’interne comme à l’externe'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité d’analyser et d’harmoniser les pratiques de promotion de l’organisation de la formation professionnelle à l’éducation nationale.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostA5_C3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A5_C3', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les acteurs socio-économiques de mon territoire. '), ('Degre_2', 'Degré 2 En tant qu’agent du service public, je construis un réseau de partenaires socio-économiques actualisé et mobilisable. '), ('Degre_3', 'Degré 3 Je suis un interlocuteur reconnu et sollicité par les acteurs socio-économiques sur un territoire.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité de mettre en relation mes pairs avec mes contacts.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostA6_C1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A6_C1', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les éléments constitutifs d’une politique commerciale d’une organisation.'), ('Degre_2', 'Degré 2 Au sein d’un collectif de travail, j’apporte des éléments d’analyse.'), ('Degre_3', 'Degré 3 J’oriente la définition des objectifs de la politique commerciale, l’identification des cibles prioritaires et l’élaboration du plan d’action commerciale.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité d’accompagner les équipes en place et transmettre une méthodologie d’élaboration de la politique commerciale.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostA6_C2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A6_C2', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les compétences et les métiers d’avenir et les grands projets de mon territoire.'), ('Degre_2', 'Degré 2 Je rédige un compte-rendu d’entretien et de détection des besoins chez les prospects.'), ('Degre_3', 'Degré 3 Je maitrise les techniques de questionnement et d’écoute active pour réaliser une phase de découverte pertinente.'), ('Degre_4', 'Degré 4 Je partage la méthodologie d’identification des opportunités repérées à l’échelle de mon territoire, de la région académique.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostA6_C3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A6_C3', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les types d’action commerciale et l’offre de prestations de ma structure et du réseau.'), ('Degre_2', 'Degré 2 Je participe aux évènements emploi-formation de mon territoire pour recueillir des besoins en compétences et réseauter.'), ('Degre_3', 'Degré 3 J’élabore la fiche produit. Je cible les prospects prioritaires.'), ('Degre_4', 'Degré 4 J’organise des manifestations à l’échelle d’un territoire.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='posta3',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='posta4',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='posta5',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='posta6',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='PostA2',
        ),
        migrations.DeleteModel(
            name='PostA3',
        ),
        migrations.DeleteModel(
            name='PostA4',
        ),
        migrations.DeleteModel(
            name='PostA5',
        ),
        migrations.DeleteModel(
            name='PostA6',
        ),
    ]
