# Generated by Django 3.2.18 on 2024-02-05 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CFPapp', '0002_auto_20240131_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posta3_c3',
            name='A3_C3',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je suis présent aux instances de concertation'), ('Degre_2', 'Degré 2 Je prépare et participe aux instances de concertation en apportant des éléments à soumettre au collectif.'), ('Degre_3', 'Degré 3 Je contribue à l’ordre du jour des instances de concertation.'), ('Degre_4', 'Degré 4 Je suis consulté sur des orientations précises par rapport à mon champ d’expertise.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.CreateModel(
            name='PostB4_C3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B4_C3', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les intérêts de l’organisation en matière de stratégie de développement.'), ('Degre_2', 'Degré 2 Au sein d’un collectif de travail, je contribue à la construction d’un argumentaire pour la négociation.'), ('Degre_3', 'Degré 3 Je construis un argumentaire pour préparer la phase de négociation.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité de modéliser les process de négociation.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostB4_C2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B4_C2', models.CharField(choices=[('Degre_1', 'Degré 1 J’identifie les savoir-faire de ma structure, du réseau pour valoriser l’offre de prestation à formaliser.'), ('Degre_2', 'Degré 2 Je repère les éléments à valoriser pour la rédaction de l’offre.'), ('Degre_3', 'Degré 3 Je maitrise les techniques rédactionnelles pour rendre l’offre de prestation lisible et attractive.'), ('Degre_4', 'Degré 4 J’organise et j’anime un comité de lecture pour valider l’attractivité de l’offre au regard des exigences.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostB4_C1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B4_C1', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les trames de réponse du client ou du commanditaire.'), ('Degre_2', 'Degré 2 Je contribue à définir les règles et conditions de présentation d’une offre de prestation.'), ('Degre_3', 'Degré 3 J’intègre les standards et les exigences réglementaires de présentation de l’offre de prestation'), ('Degre_4', 'Degré 4 Je suis un acteur ressource du réseau en capacité de valider la conformité du respect des règles'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostB3_C3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B3_C3', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les étapes de l’ingénierie de formation et les déterminants d’un dispositif de développement des compétences.'), ('Degre_2', 'Degré 2 Je m’appuie sur des ingénieries de dispositif existantes et des parcours ressources '), ('Degre_3', 'Degré 3 Je sais mobiliser une connaissance pointue de mon environnement'), ('Degre_4', 'Degré 4 Je modélise ma méthode d’élaboration de dispositifs innovants'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostB3_C2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B3_C2', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les approches innovantes dans les dispositifs de développement des compétences. '), ('Degre_2', 'Degré 2 Je contribue à identifier les approches innovantes dans un collectif de travail.'), ('Degre_3', 'Degré 3 J’ai identifié les acteurs internes et externes disposant des savoir-faire pour innover.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité de conseiller sur le choix des options méthodologiques,'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostB3_C1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B3_C1', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais la demande client.'), ('Degre_2', 'Degré 2 Je m’approprie la demande client.'), ('Degre_3', 'Degré 3 Je planifie et je coordonne le travail de conception avec les acteurs concernés.'), ('Degre_4', 'Degré 4 Je suis acteur ressource du réseau pour prendre en charge l’organisation d’un travail de conception d’une réponse.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostB2_C3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B2_C3', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les éléments constitutifs d’une étude de faisabilité.'), ('Degre_2', 'Degré 2 Je recueille les données nécessaires à l’étude de faisabilité du projet en termes de ressources humaines, techniques et financières à mobiliser.'), ('Degre_3', 'Degré 3 Je produis une étude de faisabilité à partir de l’analyse des éléments financiers, humains, pédagogiques et techniques recueillis.'), ('Degre_4', 'Degré 4 J’adapte mon étude de faisabilité à différents contextes, projets et acteurs.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostB2_C2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B2_C2', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les contraintes et les variables à prendre en compte dans la conception d’une réponse.'), ('Degre_2', 'Degré 2 Je pose des questions ciblées afin de caractériser le contexte.'), ('Degre_3', 'Degré 3 Je définis le contexte de la demande en identifiant les contraintes spécifiques qui influenceront la conception de la réponse.'), ('Degre_4', 'Degré 4 Je suis en capacité de prendre en compte les enjeux sociétaux dans l’analyse du contexte de la demande.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostB2_C1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B2_C1', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les techniques adaptées d’identification des besoins en compétences individuels ou collectifs.'), ('Degre_2', 'Degré 2 Je recueille les besoins en compétences en mobilisant les techniques adaptées'), ('Degre_3', 'Degré 3 Je conduis un entretien d’analyse de la demande permettant de clarifier et d’identifier les besoins en compétences.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource du réseau en capacité d’accompagner et de former sur les techniques d’identification des besoins '), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostB1_C3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B1_C3', models.CharField(choices=[('Degre_1', 'Degré 1 J’identifie les acteurs impliqués dans la dynamique d’évolution ou d’adaptation des pratiques pédagogiques.'), ('Degre_2', 'Degré 2 J’identifie les tendances d’évolution ou d’adaptation, j’extraie des données utiles et nécessaires au changement de pratiques pédagogiques.'), ('Degre_3', 'Degré 3 Je présente les informations clés et les évolutions à engager aux équipes impliquées, lors de réunions.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité de mutualiser ses analyses '), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostB1_C2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B1_C2', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les pratiques pédagogiques ou techno-pédagogiques actuelles au sein de ma structure et du réseau académique.'), ('Degre_2', 'Degré 2 Je sais mesurer les évolutions pédagogiques nécessaires au regard des pratiques actuelles du réseau.'), ('Degre_3', 'Degré 3 Je sélectionne en autonomie les données pertinentes permettant d’identifier les évolutions pédagogiques et techno pédagogiques à mettre en œuvre.'), ('Degre_4', 'Degré 4 Je sélectionne les données pertinentes à des fins de contribution académique, nationale.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostB1_C1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B1_C1', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les caractéristiques de la pédagogie'), ('Degre_2', 'Degré 2 J’identifie et je sélectionne, avec l’aide d’un collectif de travail de ma structure, ou du réseau académique,'), ('Degre_3', 'Degré 3 Je réalise ma veille en fonction de mes domaines d’activités.'), ('Degre_4', 'Degré 4 Je suis un acteur ressources pour le réseau en capacité de croiser différentes sources d’informations internes et externes.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
