# Generated by Django 3.2.18 on 2024-02-05 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CFPapp', '0003_auto_20240205_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostC4_C3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C4_C3', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais le cycle d’amélioration et je peux le décrire.'), ('Degre_2', 'Degré 2 J’évalue la qualité des prestations au regard du cahier des charges pour identifier les écarts et alerter sur les risques potentiels.'), ('Degre_3', 'Degré 3 J’analyse le résultat des indicateurs au sein d’un collectif et j’assure le reporting auprès du service qualité et de la direction de ma structure.'), ('Degre_4', 'Degré 4 Je suis pilote du processus d’amélioration continue de ma structure'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostC4_C2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C4_C2', models.CharField(choices=[('Degre_1', 'Degré 1 Je peux décrire le management de la qualité mis en place dans mon organisation.'), ('Degre_2', 'Degré 2 Je sais utiliser les bons documents du système qualité et je suis capable de les rapprocher d’un processus.'), ('Degre_3', 'Degré 3 Je participe au processus de veille et de respect des engagements de qualité en utilisant les moyens de pilotage de ma structure, du réseau'), ('Degre_4', 'Degré 4 Je suis un acteur ressource du réseau pour relayer les engagements qualité de l’académie'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostC4_C1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C4_C1', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais la règlementation relative aux certifications des organisations qui s’impose à tous les prestataires'), ('Degre_2', 'Degré 2 J’identifie l’application et le respect des exigences et indicateurs de performances de l’organisation.'), ('Degre_3', 'Degré 3 Je peux présenter à mes collaborateurs et à mes partenaires les engagements du label et leur déclinaison au niveau de la structure'), ('Degre_4', 'Degré 4 Je conseille sur l’évolution de la politique qualité mise en place au niveau de ma structure, au niveau du réseau académique.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostC3_C3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C3_C3', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les techniques d’animation et de coopération'), ('Degre_2', 'Degré 2 Je participe aux instances du partenariat et je contribue à leur animation.'), ('Degre_3', 'Degré 3 Je pilote en responsabilité des instances, j’anime des groupes de travail conformément aux engagements mutuels.'), ('Degre_4', 'Degré 4 Je suis un interlocuteur repéré au niveau de ma structure, du réseau pour l’animation de partenariats d’envergure régionale, nationale et européenne.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostC3_C2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C3_C2', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les différentes formes juridiques des partenariats'), ('Degre_2', 'Degré 2 Je participe à un premier temps d’échanges sur l’objet du partenariat à construire.'), ('Degre_3', 'Degré 3 En accord avec les décideurs de ma structure, du réseau, je négocie avec les partenaires les composantes techniques et pédagogiques'), ('Degre_4', 'Degré 4 Sur sollicitation du DRAFPIC, je rédige et je propose les accords de groupement de consortium pour un AMI, un AAP.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostC3_C1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C3_C1', models.CharField(choices=[('Degre_1', 'Degré 1 J’ai identifié les partenaires potentiels de mon territoire : concurrents, prescripteurs, OPCO, certificateurs, entreprises, collectivités territoriales'), ('Degre_2', 'Degré 2 Je rencontre les partenaires de mon territoire pour me présenter, présenter l’offre de services de ma structure, du réseau '), ('Degre_3', 'Degré 3 J’identifie les complémentarités pour un projet nécessitant une réponse partenariale.'), ('Degre_4', 'Degré 4 Je valorise les complémentarités pour un projet d’envergure régional, national nécessitant une réponse partenariale.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostC2_C3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C2_C3', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais la cartographie des compétences mise à disposition par le service RH de ma structure.'), ('Degre_2', 'Degré 2 Je repère et je mesure les besoins en compétences des collaborateurs administratifs et pédagogiques mobilisés '), ('Degre_3', 'Degré 3 Je vérifie que les compétences existantes des collaborateurs sont en adéquation avec les besoins des projets que je manage.'), ('Degre_4', 'Degré 4 Je contribue à l’évolution de la cartographie des compétences des acteurs de ma structure et du réseau.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostC2_C2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C2_C2', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les techniques et les outils d’animation et de management variés'), ('Degre_2', 'Degré 2 Je contribue au choix de techniques d’animation facilitant l’engagement coopératif de l’équipe.'), ('Degre_3', 'Degré 3 Je veille à l’engagement de l’équipe en mobilisant les techniques appropriées et en adaptant ma posture.'), ('Degre_4', 'Degré 4 Je tire les enseignements des méthodes et techniques mises en œuvre et propose des améliorations.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostC2_C1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C2_C1', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais l’organigramme, les fonctions et les missions de chacun dans ma structure.'), ('Degre_2', 'Degré 2 Je contribue à la mobilisation de l’équipe en expliquant les enjeux du projet.'), ('Degre_3', 'Degré 3 Je mobilise une équipe sur la durée du projet jusqu’à l’atteinte des objectifs.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité de mobiliser des équipes sur des projets d’envergure académique, nationale '), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostC1_C3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C1_C3', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les modalités et les indicateurs d’évaluation de projets déjà mis en œuvre.'), ('Degre_2', 'Degré 2 J’utilise les outils d’évaluation et de suivi mis à disposition par ma structure, le réseau académique'), ('Degre_3', 'Degré 3 J’anime des points d’étape de réalisation du projet afin de mesurer l’état d’avancement, les écarts éventuels et les actions correctives.'), ('Degre_4', 'Degré 4 Je suis un acteur ressources pour le réseau en capacité de suivre et d’évaluer des projets d’envergure régionale, nationale, européenne, des projets impliquant des partenaires.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostC1_C2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C1_C2', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les acteurs et les moyens existants de mon organisation'), ('Degre_2', 'Degré 2 Je repère les acteurs de mon organisation et les partenaires externes mobilisables pour le projet'), ('Degre_3', 'Degré 3 J’estime les moyens humains et matériels nécessaires au projet en sollicitant les acteurs experts de ma structure et du réseau académique.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour ma structure,'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostC1_C1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C1_C1', models.CharField(choices=[('Degre_1', 'Degré 1 Je connais la démarche de projet'), ('Degre_2', 'Degré 2 Je participe à l’élaboration d’un projet dans toutes ses composantes'), ('Degre_3', 'Degré 3 Je réalise une étude d’impact et de faisabilité.'), ('Degre_4', 'Degré 4 Je pilote des projets complexes d’envergure académique, nationale sur des secteurs particuliers'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
