# Generated by Django 3.2.18 on 2024-02-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFPapp', '0004_postc1_c1_postc1_c2_postc1_c3_postc2_c1_postc2_c2_postc2_c3_postc3_c1_postc3_c2_postc3_c3_postc4_c1_'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur_infos',
            name='greta_rattachement',
        ),
        migrations.AddField(
            model_name='utilisateur_infos',
            name='fonction',
            field=models.CharField(choices=[('GRM', 'CFP au Greta Rouen Maritime'), ('GPN', 'CFP au Greta Portes Normandes'), ('GCN', 'CFP au Greta Côtes Normandes'), ('DDAT', 'DDAT'), ('DRFPIC', 'CFP DRFPIC'), ('IFPRA', 'CFP IFPRA')], default='GRM', max_length=20),
        ),
    ]
