# Generated by Django 3.2.18 on 2024-02-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFPapp', '0005_auto_20240212_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur_infos',
            name='age',
        ),
        migrations.RemoveField(
            model_name='utilisateur_infos',
            name='codepostal',
        ),
        migrations.RemoveField(
            model_name='utilisateur_infos',
            name='commune',
        ),
    ]
