# Generated by Django 3.2.18 on 2024-02-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFPapp', '0006_auto_20240212_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posta2_c1',
            name='A2_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 J’ai mis en œuvre la démarche de diagnostic lors de mon année probatoire.'), ('Degre_2', 'Degré 2 Je planifie et organise ma démarche de diagnostic.'), ('Degre_3', 'Degré 3 Je conçois le plan d’action : identification des acteurs clés, choix des outils d’investigations'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité d’accompagner mes pairs sur la structuration et la démarche de diagnostic'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='posta2_c3',
            name='A2_C3',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les différents types de note et je connais la structure d’une note ou d’un document d’analyse.'), ('Degre_2', 'Degré 2 Je repère les éléments de mon diagnostic à intégrer dans une note d’opportunité'), ('Degre_3', 'Degré 3 Je produis régulièrement des notes et des documents d’analyse en toute autonomie.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité d’accompagner des pairs à la production de notes et de documents d’analyse.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='posta3_c1',
            name='A3_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les éléments qui positionne une structure sur le marché de la formation professionnelle '), ('Degre_2', 'Degré 2 Je sais positionner mon organisation dans le cadre réglementaire et législatif de la formation professionnelle.'), ('Degre_3', 'Degré 3 J’analyse le positionnement des acteurs du marché.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource du réseau en capacité de former mes pairs '), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='posta3_c2',
            name='A3_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je m’informe des résultats, des diagnostics, des enquêtes réalisés et des analyses produites '), ('Degre_2', ' Degré 2 J’identifie les potentiels de développement à court, moyen et long terme à partir diagnostic '), ('Degre_3', 'Degré 3 Je propose des axes de développement concrets'), ('Degre_4', 'Degré 4 Je capitalise et je mutualise les analyses réalisées pour ma structure, le réseau académique'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='posta3_c3',
            name='A3_C3',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je prends connaissance des comptes-rendus des différentes instances.'), ('Degre_2', 'Degré 2 Je participe aux instances de concertation et je contribue aux échanges'), ('Degre_3', 'Degré 3 Je contribue à l’ordre du jour des instances de concertation.'), ('Degre_4', 'Degré 4 Dans les instances de concertation à l’interne, je suis consulté sur des orientations'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='posta4_c3',
            name='A4_C3',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les outils de communication adaptés au conseil : synthèse, note d’opportunité, rapport, etc.'), ('Degre_2', 'Degré 2 Je choisis les outils de communication adaptés aux décideurs.'), ('Degre_3', 'Degré 3 Je propose à l’écrit ou à l’oral un contenu synthétique pour être lu ou entendu par les décideurs.'), ('Degre_4', 'Degré 4 A la demande des décideurs, je rédige et je présente un rapport circonstancié'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='posta5_c2',
            name='A5_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je distingue les 3 voies de formation professionnelle. Je m’informe en interne sur les missions, l’offre et les moyens des structures'), ('Degre_2', 'Degré 2 J’identifie sur mon territoire l’offre de formations.'), ('Degre_3', 'Degré 3 Je sais argumenter les spécificités et les atouts de mon organisation, à l’interne comme à l’externe'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité d’analyser et d’harmoniser les pratiques de promotion de l’organisation de la formation professionnelle à l’éducation nationale.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='posta5_c3',
            name='A5_C3',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les acteurs socio-économiques de mon territoire. '), ('Degre_2', 'Degré 2 En tant qu’agent du service public, je construis un réseau de partenaires socio-économiques actualisé et mobilisable. '), ('Degre_3', 'Degré 3 Je suis un interlocuteur reconnu et sollicité par les acteurs socio-économiques sur un territoire.'), ('Degre_4', 'Degré 4 Je suis à l’initiative de rencontres partenariales sur un projet donné.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='posta6_c1',
            name='A6_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les éléments constitutifs d’une politique commerciale d’une organisation.'), ('Degre_2', 'Degré 2 J’apporte des éléments d’analyse permettant l’évolution de la politique commerciale'), ('Degre_3', 'Degré 3 J’oriente la définition des objectifs de la politique commerciale, l’identification des cibles prioritaires et l’élaboration du plan d’action commerciale.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité d’accompagner les équipes en place et transmettre une méthodologie d’élaboration de la politique commerciale.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='posta6_c2',
            name='A6_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les compétences et les métiers d’avenir et les grands projets de mon territoire.'), ('Degre_2', 'Degré 2 Je rédige un compte-rendu d’entretien et de détection des besoins chez les prospects.'), ('Degre_3', 'Degré 3 Je maitrise les techniques de questionnement et d’écoute active pour réaliser une phase de découverte pertinente.'), ('Degre_4', 'Degré 4 Je partage la méthodologie d’identification des opportunités'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
    ]
