# Generated by Django 3.2.18 on 2024-02-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFPapp', '0009_auto_20240226_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='A2_CO_01',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je mets en œuvre la démarche de diagnostic lors de mon année probatoire'), ('Degre_2', 'Degré 2 Je repère les enjeux, attentes et besoins du commanditaire.'), ('Degre_3', 'Degré 3 J’organise ma démarche de diagnostic : identification des acteurs clés, choix des outils d’investigations'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité d’accompagner mes pairs sur la structuration et la démarche de diagnostic'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postb1_c1',
            name='B1_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je repère les sources d’informations pédagogiques'), ('Degre_2', 'Degré 2 J’identifie et je sélectionne, les sources d’informations me permettant de recenser des évolutions '), ('Degre_3', 'Degré 3 Je réalise ma veille en fonction de mes domaines d’activités.'), ('Degre_4', 'Degré 4 Je suis un acteur ressources pour le réseau en capacité de croiser différentes sources d’informations'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postb1_c2',
            name='B1_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je m’informe sur les orientations pédagogiques ou techno-pédagogiques.'), ('Degre_2', 'Degré 2 Je mesure les évolutions pédagogiques nécessaires au regard des pratiques actuelles du réseau.'), ('Degre_3', 'Degré 3 Je sélectionne en autonomie les données pertinentes permettant d’identifier les évolutions'), ('Degre_4', 'Degré 4 Je sélectionne les données pertinentes à des fins de contribution académique, nationale.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postb1_c3',
            name='B1_C3',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 J’identifie les acteurs impliqués dans la dynamique d’évolution ou d’adaptation des pratiques pédagogiques.'), ('Degre_2', 'Degré 2 J’identifie les tendances d’évolution ou d’adaptation'), ('Degre_3', 'Degré 3 Je présente les informations clés et les évolutions à engager aux équipes impliquées, lors de réunions.'), ('Degre_4', 'Degré 4 Je partage les informations clés et les évolutions à engager avec les équipes impliquées, lors de réunions.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postb2_c1',
            name='B2_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les techniques d’identification des besoins en compétences individuels ou collectifs.'), ('Degre_2', 'Degré 2 Je recueille les besoins en compétences en mobilisant les techniques adaptées'), ('Degre_3', 'Degré 3 Je conduis un entretien d’analyse de la demande permettant de clarifier et d’identifier les besoins en compétences.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource du réseau en capacité d’accompagner et de former sur les techniques d’identification des besoins '), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postb2_c2',
            name='B2_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais -\tles éléments qualifiant le contexte d’une demande.'), ('Degre_2', 'Degré 2 Je pose des questions ciblées ou bien je décrypte les différens supports.'), ('Degre_3', 'Degré 3 Je vérifie ma compréhension du contexte en reformulant la demande.'), ('Degre_4', 'Degré 4 Je prends en compte la pluralité des enjeux dans l’analyse du contexte de la demande.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postb2_c3',
            name='B2_C3',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les éléments constitutifs d’une étude de faisabilité.'), ('Degre_2', 'Degré 2 Je recueille les données nécessaires à l’étude de faisabilité du projet'), ('Degre_3', 'Degré 3 Je produis une étude de faisabilité à partir de l’analyse des éléments financiers, humains, pédagogiques et techniques'), ('Degre_4', 'Degré 4 J’adapte mon étude de faisabilité à différents contextes, projets et acteurs.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postb3_c1',
            name='B3_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 A partir de la demande client, je prends connaissance des ressources utiles '), ('Degre_2', 'Degré 2 A partir de la demande client, je participe à une réunion avec les acteurs internes et/ou externes'), ('Degre_3', 'Degré 3 Je planifie et je coordonne le travail de conception avec les acteurs concernés.'), ('Degre_4', 'Degré 4 Je suis acteur ressource du réseau pour prendre en charge l’organisation d’un travail de conception d’une réponse.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postb3_c2',
            name='B3_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les approches innovantes dans les dispositifs de développement des compétences.'), ('Degre_2', 'Degré 2 J’étudie les options méthodologiques, pédagogiques, techniques et financières adaptées au projet.'), ('Degre_3', 'Degré 3 J’identifie les acteurs internes et externes disposant des savoir-faire pour innover.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité de conseiller sur le choix des options méthodologiques,'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postb3_c3',
            name='B3_C3',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les étapes de l’ingénierie de formation et les déterminants d’un dispositif de développement des compétences.'), ('Degre_2', 'Degré 2 Je m’appuie sur des ingénieries existantes et des parcours ressources '), ('Degre_3', 'Degré 3 Je construis le dispositif à partir des options choisies en m’assurant de répondre aux exigences'), ('Degre_4', 'Degré 4 Je modélise ma méthode d’élaboration de dispositifs innovants'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
    ]
