# Generated by Django 3.2.18 on 2024-02-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFPapp', '0010_auto_20240227_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postc1_c1',
            name='C1_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais la démarche de projet'), ('Degre_2', 'Degré 2 Je participe à l’élaboration d’un projet dans toutes ses composantes'), ('Degre_3', 'Degré 3 Je pilote des projets à l’échelle de ma structure'), ('Degre_4', 'Degré 4 Je pilote des projets complexes d’envergure académique, nationale sur des secteurs particuliers'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postc2_c1',
            name='C2_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais l’organigramme, les fonctions et les missions de chacun dans ma structure.'), ('Degre_2', 'Degré 2 Je mobilise une équipe sur la durée du projet jusqu’à l’atteinte des objectifs'), ('Degre_3', 'Degré 3 Je fédère les équipes autour d’un sens partagé en expliquant les enjeux et l’ingénierie du projet.'), ('Degre_4', 'Degré 4 JJe suis un acteur ressource pour le réseau en capacité de mobiliser des équipes'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postc2_c2',
            name='C2_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je me familiarise aux techniques et aux outils d’animation et de management variés.'), ('Degre_2', 'Degré 2 J’applique les techniques d’animation facilitant l’engagement coopératif des équipes.'), ('Degre_3', 'Degré 3 J’utilise les techniques de management en adoptant une posture bienveillante'), ('Degre_4', 'Degré 4 J’évalue les méthodes et techniques mises en œuvre et propose des améliorations.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postc2_c3',
            name='C2_C3',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais -\tles ressources mises à disposition par le service RH.'), ('Degre_2', 'Degré 2 J’identifie les compétences acquises des collaborateurs administratifs et pédagogiques'), ('Degre_3', 'Degré 3 J’anticipe les besoins en compétences et j’identifie celles manquantes, au regard de l’évolution de mon offre.'), ('Degre_4', 'Degré 4 Je contribue à l’évolution de la cartographie des compétences des acteurs de ma structure et du réseau.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postc3_c1',
            name='C3_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 J’identifie les partenaires potentiels de mon territoire : concurrents, prescripteurs, OPCO, certificateurs, entreprises, collectivités territoriales'), ('Degre_2', 'Degré 2 Je rencontre les partenaires de mon territoire pour me présenter et partager nos offres de service respectives.'), ('Degre_3', 'Degré 3 J’active mon réseau pour répondre aux problématiques du territoire.'), ('Degre_4', 'Degré 4 Je valorise les complémentarités pour un projet d’envergure régionale, nationale nécessitant une réponse partenariale.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postc3_c2',
            name='C3_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les différentes formes juridiques des partenariats'), ('Degre_2', 'Degré 2 Je participe à un premier temps d’échanges sur l’objet du partenariat à construire.'), ('Degre_3', 'Degré 3 Je participe à la détection des complémentarités et des économies d’échelle que je présente aux décideurs de ma structure, du réseau.'), ('Degre_4', 'Degré 4 Sur sollicitation du DRAFPIC, je propose des accords de groupement de consortium.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postc4_c2',
            name='C4_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je peux décrire le management de la qualité mis en place dans mon organisation.'), ('Degre_2', 'Degré 2 J’utilise les bons documents du système qualité et je suis capable de les rapprocher d’un processus.'), ('Degre_3', 'Degré 3 Je participe au processus de veille et de respect des engagements de qualité en utilisant les moyens de pilotage de ma structure, du réseau'), ('Degre_4', 'Degré 4 Je suis un acteur ressource du réseau pour relayer les engagements qualité de l’académie'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
    ]
