# Generated by Django 3.2.18 on 2024-03-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFPapp', '0011_auto_20240229_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur_infos',
            name='anciennete',
        ),
        migrations.AddField(
            model_name='utilisateur_infos',
            name='anciennete_annee',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='utilisateur_infos',
            name='anciennete_mois',
            field=models.IntegerField(default=1),
        ),
    ]
