# Generated by Django 3.2.18 on 2024-03-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFPapp', '0012_auto_20240312_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur_infos',
            name='anciennete_annee',
        ),
        migrations.RemoveField(
            model_name='utilisateur_infos',
            name='anciennete_mois',
        ),
        migrations.AddField(
            model_name='utilisateur_infos',
            name='anciennete',
            field=models.IntegerField(default=0),
        ),
    ]
