# Generated by Django 3.2.18 on 2024-03-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFPapp', '0017_alter_user_infos_fonction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_infos',
            name='fonction',
            field=models.CharField(choices=[('', 'Choisir votre fonction actuelle '), ('GRM', 'CFP au Greta Rouen Maritime'), ('GPN', 'CFP au Greta Portes Normandes'), ('GCN', 'CFP au Greta Côtes Normandes'), ('DDAT', 'DDAT'), ('DRFPIC', 'CFP DRFPIC'), ('IFPRA', 'CFP IFPRA')], max_length=20),
        ),
    ]
