# Generated by Django 3.2.18 on 2024-03-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CFPapp', '0018_alter_user_infos_fonction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_infos',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='user_infos',
            name='prenom',
        ),
    ]
