# Generated by Django 3.2.18 on 2024-03-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFPapp', '0020_auto_20240318_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postb1_c1',
            name='B1_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je repère les sources d’informations pédagogiques.'), ('Degre_2', 'Degré 2 J’identifie et je sélectionne les sources d’informations me permettant de recenser des évolutions.'), ('Degre_3', 'Degré 3 Je réalise ma veille en fonction de mes domaines d’activités.'), ('Degre_4', 'Degré 4 Je suis un acteur ressources pour le réseau en capacité de croiser différentes sources d’informations.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postb1_c2',
            name='B1_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je m’informe sur les orientations pédagogiques ou techno-pédagogiques.'), ('Degre_2', 'Degré 2 Je mesure les évolutions pédagogiques nécessaires au regard des pratiques actuelles du réseau.'), ('Degre_3', 'Degré 3 Je sélectionne en autonomie les données pertinentes permettant d’identifier les évolutions.'), ('Degre_4', 'Degré 4 Je sélectionne les données pertinentes à des fins de contribution académique, nationale.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postb2_c2',
            name='B2_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les éléments qualifiant le contexte d’une demande.'), ('Degre_2', 'Degré 2 Je pose des questions ciblées ou bien je décrypte les différens supports.'), ('Degre_3', 'Degré 3 Je vérifie ma compréhension du contexte en reformulant la demande.'), ('Degre_4', 'Degré 4 Je prends en compte la pluralité des enjeux dans l’analyse du contexte de la demande.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postb2_c3',
            name='B2_C3',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les éléments constitutifs d’une étude de faisabilité.'), ('Degre_2', 'Degré 2 Je recueille les données nécessaires à l’étude de faisabilité du projet.'), ('Degre_3', 'Degré 3 Je produis une étude de faisabilité à partir de l’analyse des éléments financiers, humains, pédagogiques et techniques.'), ('Degre_4', 'Degré 4 J’adapte mon étude de faisabilité à différents contextes, projets et acteurs.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postb3_c1',
            name='B3_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 A partir de la demande client, je prends connaissance des ressources utiles.'), ('Degre_2', 'Degré 2 A partir de la demande client, je participe à une réunion avec les acteurs internes et/ou externes.'), ('Degre_3', 'Degré 3 Je planifie et je coordonne le travail de conception avec les acteurs concernés.'), ('Degre_4', 'Degré 4 Je suis acteur ressource du réseau pour prendre en charge l’organisation d’un travail de conception d’une réponse.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postb3_c2',
            name='B3_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les approches innovantes dans les dispositifs de développement des compétences.'), ('Degre_2', 'Degré 2 J’étudie les options méthodologiques, pédagogiques, techniques et financières adaptées au projet.'), ('Degre_3', 'Degré 3 J’identifie les acteurs internes et externes disposant des savoir-faire pour innover.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité de conseiller sur le choix des options méthodologiques.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postb3_c3',
            name='B3_C3',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les étapes de l’ingénierie de formation et les déterminants d’un dispositif de développement des compétences.'), ('Degre_2', 'Degré 2 Je m’appuie sur des ingénieries existantes et des parcours ressources.'), ('Degre_3', 'Degré 3 Je construis le dispositif à partir des options choisies en m’assurant de répondre aux exigences.'), ('Degre_4', 'Degré 4 Je modélise ma méthode d’élaboration de dispositifs innovants.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postb4_c1',
            name='B4_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les trames de réponse du client ou du commanditaire.'), ('Degre_2', 'Degré 2 Je contribue à définir les règles et conditions de présentation d’une offre de prestation.'), ('Degre_3', 'Degré 3 J’intègre les standards et les exigences réglementaires de présentation de l’offre de prestation.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource du réseau en capacité de valider la conformité du respect des règles.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
    ]
