# Generated by Django 3.2.18 on 2024-03-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFPapp', '0021_auto_20240318_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postb1_c3',
            name='B1_C3',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 J’identifie les acteurs impliqués dans la dynamique d’évolution ou d’adaptation des pratiques pédagogiques.'), ('Degre_2', 'Degré 2 J’identifie les tendances d’évolution ou d’adaptation.'), ('Degre_3', 'Degré 3 Je présente les informations clés et les évolutions à engager aux équipes impliquées, lors de réunions.'), ('Degre_4', 'Degré 4 Je partage les informations clés et les évolutions à engager avec les équipes impliquées, lors de réunions.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postb2_c1',
            name='B2_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les techniques d’identification des besoins en compétences individuels ou collectifs.'), ('Degre_2', 'Degré 2 Je recueille les besoins en compétences en mobilisant les techniques adaptées.'), ('Degre_3', 'Degré 3 Je conduis un entretien d’analyse de la demande permettant de clarifier et d’identifier les besoins en compétences.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource du réseau en capacité d’accompagner et de former sur les techniques d’identification des besoins '), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postc1_c1',
            name='C1_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais la démarche de projet.'), ('Degre_2', 'Degré 2 Je participe à l’élaboration d’un projet dans toutes ses composantes.'), ('Degre_3', 'Degré 3 Je pilote des projets à l’échelle de ma structure.'), ('Degre_4', 'Degré 4 Je pilote des projets complexes d’envergure académique, nationale sur des secteurs particuliers.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postc1_c2',
            name='C1_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les acteurs et les moyens existants de mon organisation.'), ('Degre_2', 'Degré 2 Je repère les acteurs de mon organisation et les partenaires externes mobilisables pour le projet.'), ('Degre_3', 'Degré 3 J’estime les moyens humains et matériels nécessaires au projet en sollicitant les acteurs experts de ma structure et du réseau académique.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour ma structure.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postc1_c3',
            name='C1_C3',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les modalités et les indicateurs d’évaluation de projets déjà mis en œuvre.'), ('Degre_2', 'Degré 2 J’utilise les outils d’évaluation et de suivi mis à disposition par ma structure, le réseau académique.'), ('Degre_3', 'Degré 3 J’anime des points d’étape de réalisation du projet afin de mesurer l’état d’avancement, les écarts éventuels et les actions correctives.'), ('Degre_4', 'Degré 4 Je suis un acteur ressources pour le réseau en capacité de suivre et d’évaluer des projets d’envergure régionale, nationale, européenne, des projets impliquant des partenaires.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postc2_c2',
            name='C2_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je me familiarise aux techniques et aux outils d’animation et de management variés.'), ('Degre_2', 'Degré 2 J’applique les techniques d’animation facilitant l’engagement coopératif des équipes.'), ('Degre_3', 'Degré 3 J’utilise les techniques de management en adoptant une posture bienveillante.'), ('Degre_4', 'Degré 4 J’évalue les méthodes et techniques mises en œuvre et propose des améliorations.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postc2_c3',
            name='C2_C3',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais -\tles ressources mises à disposition par le service RH.'), ('Degre_2', 'Degré 2 J’identifie les compétences acquises des collaborateurs administratifs et pédagogiques.'), ('Degre_3', 'Degré 3 J’anticipe les besoins en compétences et j’identifie celles manquantes, au regard de l’évolution de mon offre.'), ('Degre_4', 'Degré 4 Je contribue à l’évolution de la cartographie des compétences des acteurs de ma structure et du réseau.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postc3_c1',
            name='C3_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 J’identifie les partenaires potentiels de mon territoire : concurrents, prescripteurs, OPCO, certificateurs, entreprises, collectivités territoriales.'), ('Degre_2', 'Degré 2 Je rencontre les partenaires de mon territoire pour me présenter et partager nos offres de service respectives.'), ('Degre_3', 'Degré 3 J’active mon réseau pour répondre aux problématiques du territoire.'), ('Degre_4', 'Degré 4 Je valorise les complémentarités pour un projet d’envergure régionale, nationale nécessitant une réponse partenariale.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postc3_c2',
            name='C3_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les différentes formes juridiques des partenariats.'), ('Degre_2', 'Degré 2 Je participe à un premier temps d’échanges sur l’objet du partenariat à construire.'), ('Degre_3', 'Degré 3 Je participe à la détection des complémentarités et des économies d’échelle que je présente aux décideurs de ma structure, du réseau.'), ('Degre_4', 'Degré 4 Sur sollicitation du DRAFPIC, je propose des accords de groupement de consortium.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postc3_c3',
            name='C3_C3',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les techniques d’animation et de coopération.'), ('Degre_2', 'Degré 2 Je participe aux instances du partenariat et je contribue à leur animation.'), ('Degre_3', 'Degré 3 Je pilote en responsabilité des instances, j’anime des groupes de travail conformément aux engagements mutuels.'), ('Degre_4', 'Degré 4 Je suis un interlocuteur repéré au niveau de ma structure, du réseau pour l’animation de partenariats d’envergure régionale, nationale et européenne.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postc4_c1',
            name='C4_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais la règlementation relative aux certifications des organisations qui s’impose à tous les prestataires.'), ('Degre_2', 'Degré 2 J’identifie l’application et le respect des exigences et indicateurs de performances de l’organisation.'), ('Degre_3', 'Degré 3 Je peux présenter à mes collaborateurs et à mes partenaires les engagements du label et leur déclinaison au niveau de la structure.'), ('Degre_4', 'Degré 4 Je conseille sur l’évolution de la politique qualité mise en place au niveau de ma structure, au niveau du réseau académique.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postc4_c2',
            name='C4_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je peux décrire le management de la qualité mis en place dans mon organisation.'), ('Degre_2', 'Degré 2 J’utilise les bons documents du système qualité et je suis capable de les rapprocher d’un processus.'), ('Degre_3', 'Degré 3 Je participe au processus de veille et de respect des engagements de qualité en utilisant les moyens de pilotage de ma structure, du réseau.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource du réseau pour relayer les engagements qualité de l’académie.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='postc4_c3',
            name='C4_C3',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais le cycle d’amélioration et je peux le décrire.'), ('Degre_2', 'Degré 2 J’évalue la qualité des prestations au regard du cahier des charges pour identifier les écarts et alerter sur les risques potentiels.'), ('Degre_3', 'Degré 3 J’analyse le résultat des indicateurs au sein d’un collectif et j’assure le reporting auprès du service qualité et de la direction de ma structure.'), ('Degre_4', 'Degré 4 Je suis pilote du processus d’amélioration continue de ma structure.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
    ]
