# Generated by Django 3.2.18 on 2024-03-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFPapp', '0022_auto_20240318_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posta1_c1',
            name='A1_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais mon environnement proche de travail.'), ('Degre_2', 'Degré 2 Je participe aux instances chargées de définir la stratégie de veille.'), ('Degre_3', 'Degré 3 Je suis force de proposition pour mettre en place une stratégie de veille au service du développement de ma structure.'), ('Degre_4', 'Degré 4 Je contribue à l’organisation du système de veille dans les phases de collecte, traitement et diffusion.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='posta1_c2',
            name='A1_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 J’évalue la fiabilité d’une source, crédibilité et réputation.'), ('Degre_2', 'Degré 2 Je sélectionne les sources les plus pertinentes au regard de mes missions et de la stratégie de ma structure.'), ('Degre_3', 'Degré 3 J’évalue la complétude de ma veille. Pour compléter ma veille j’identifie de nouveaux acteurs.'), ('Degre_4', 'Degré 4 Je conseille les décideurs sur la recherche de prestataires et d’outils performants de veille.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='posta2_c2',
            name='A2_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je sélectionne et je fais apparaitre les données de mon territoire ou de mes secteurs d’activités.'), ('Degre_2', 'Degré 2 Je contextualise les données à l’échelle de la problématique.'), ('Degre_3', 'Degré 3 J’extraie et j’exploite les données pertinentes afin d’identifier les besoins en compétences.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité d’accompagner un collectif de travail pour produire des analyses concertées.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='posta2_c3',
            name='A2_C3',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les différents types de note et je connais la structure d’une note ou d’un document d’analyse.'), ('Degre_2', 'Degré 2 Je repère les éléments de mon diagnostic à intégrer dans une note d’opportunité.'), ('Degre_3', 'Degré 3 Je produis régulièrement des notes et des documents d’analyse en toute autonomie.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité d’accompagner des pairs à la production de notes et de documents d’analyse.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='posta3_c2',
            name='A3_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je m’informe des résultats, des diagnostics, des enquêtes réalisés et des analyses produites.'), ('Degre_2', ' Degré 2 J’identifie les potentiels de développement à court, moyen et long terme'), ('Degre_3', 'Degré 3 Je propose des axes de développement concrets.'), ('Degre_4', 'Degré 4 Je capitalise et je mutualise les analyses réalisées pour ma structure, le réseau académique.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='posta6_c1',
            name='A6_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais les éléments constitutifs d’une politique commerciale d’une organisation.'), ('Degre_2', 'Degré 2 J’apporte des éléments d’analyse permettant l’évolution de la politique commerciale.'), ('Degre_3', 'Degré 3 Je contribue à la définition des objectifs de la politique commerciale.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité d’accompagner les équipes en place et transmettre une méthodologie.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
        migrations.AlterField(
            model_name='posta6_c2',
            name='A6_C2',
            field=models.CharField(choices=[('Degre_1', "Degré 1 Je m'informe sur les compétences et les métiers d’avenir et les grands projets de mon territoire."), ('Degre_2', 'Degré 2 Je rédige un compte-rendu d’entretien et de détection des besoins chez les prospects.'), ('Degre_3', 'Degré 3 Je maitrise les techniques de questionnement et d’écoute active pour identifier les besoins des structures rencontrées.'), ('Degre_4', 'Degré 4 Je partage la méthodologie d’identification des opportunités.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
    ]
