# Generated by Django 3.2.18 on 2024-03-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFPapp', '0023_auto_20240319_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postc2_c1',
            name='C2_C1',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je connais l’organigramme, les fonctions et les missions de chacun dans ma structure.'), ('Degre_2', 'Degré 2 Je mobilise une équipe sur la durée du projet jusqu’à l’atteinte des objectifs'), ('Degre_3', 'Degré 3 Je fédère les équipes autour d’un sens partagé en expliquant les enjeux et l’ingénierie du projet.'), ('Degre_4', 'Degré 4 Je suis un acteur ressource pour le réseau en capacité de mobiliser des équipes'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
    ]
