# Generated by Django 3.2.18 on 2024-03-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CFPapp', '0024_alter_postc2_c1_c2_c1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='A3_C2',
            field=models.CharField(choices=[('Degre_1', 'Degré 1 Je m’informe des résultats, des diagnostics, des enquêtes réalisés et des analyses produites.'), ('Degre_2', ' Degré 2J’identifie les potentiels de développement à court, moyen et long terme à partir du diagnostic précis.'), ('Degre_3', 'Degré 3 Je propose des axes de développement concrets (moyens et ressources à mobiliser, points de vigilances).'), ('Degre_4', 'Degré 4 Je capitalise et je mutualise les analyses réalisées pour ma structure, le réseau académique.'), ('N_S_P', 'Ne se prononce pas')], default='Degre_1', max_length=20),
        ),
    ]
