# Generated by Django 3.2.18 on 2024-04-07 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CFPapp', '0025_alter_post_a3_c2'),
    ]

    operations = [
        migrations.CreateModel(
            name='CFP_infos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anciennete_annee', models.IntegerField()),
                ('anciennete_mois', models.IntegerField()),
                ('fonction', models.CharField(choices=[('', 'Choisir votre fonction actuelle '), ('GRM', 'CFP au Greta Rouen Maritime'), ('GPN', 'CFP au Greta Portes Normandes'), ('GCN', 'CFP au Greta Côtes Normandes'), ('DDAT', 'DDAT'), ('DRFPIC', 'CFP DRFPIC'), ('IFPRA', 'CFP IFPRA')], max_length=20)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
