from django.urls import include, path
from django.contrib.auth import views as auth_views
import urllib3
from CFPapp import views
from CFPsite import urls
from .views import *


urlpatterns = [
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('cfpinfos/', views.cfpinfos, name='cfpinfos'),
    path('all_cfp/', views.all_cfp, name='all_cfp'),
    path('erase_user_data/', erase_user_data, name='erase_user_data'),
    path('step1_A1/', step1_A1, name='step1_A1'),
    path('step2_A1/', step2_A1, name='step2_A1'),
    path('step3_A1/', step3_A1, name='step3_A1'),
    path('step1_A2/', step1_A2, name='step1_A2'),
    path('step2_A2/', step2_A2, name='step2_A2'),
    path('step3_A2/', step3_A2, name='step3_A2'),
    path('step1_A3/', step1_A3, name='step1_A3'),
    path('step2_A3/', step2_A3, name='step2_A3'),
    path('step3_A3/', step3_A3, name='step3_A3'),
    path('step1_A4/', step1_A4, name='step1_A4'),
    path('step2_A4/', step2_A4, name='step2_A4'),
    path('step3_A4/', step3_A4, name='step3_A4'),
    path('step1_A5/', step1_A5, name='step1_A5'),
    path('step2_A5/', step2_A5, name='step2_A5'),
    path('step3_A5/', step3_A5, name='step3_A5'),
    path('step1_A6/', step1_A6, name='step1_A6'),
    path('step2_A6/', step2_A6, name='step2_A6'),
    path('step3_A6/', step3_A6, name='step3_A6'),
    path('step1_B1/', step1_B1, name='step1_B1'),
    path('step2_B1/', step2_B1, name='step2_B1'),
    path('step3_B1/', step3_B1, name='step3_B1'),
    path('step1_B2/', step1_B2, name='step1_B2'),
    path('step2_B2/', step2_B2, name='step2_B2'),
    path('step3_B2/', step3_B2, name='step3_B2'),
    path('step1_B3/', step1_B3, name='step1_B3'),
    path('step2_B3/', step2_B3, name='step2_B3'),
    path('step3_B3/', step3_B3, name='step3_B3'),
    path('step1_B4/', step1_B4, name='step1_B4'),
    path('step2_B4/', step2_B4, name='step2_B4'),
    path('step3_B4/', step3_B4, name='step3_B4'),
    path('step1_C1/', step1_C1, name='step1_C1'),
    path('step2_C1/', step2_C1, name='step2_C1'),
    path('step3_C1/', step3_C1, name='step3_C1'),
    path('step1_C2/', step1_C2, name='step1_C2'),
    path('step2_C2/', step2_C2, name='step2_C2'),
    path('step3_C2/', step3_C2, name='step3_C2'),
    path('step1_C3/', step1_C3, name='step1_C3'),
    path('step2_C3/', step2_C3, name='step2_C3'),
    path('step3_C3/', step3_C3, name='step3_C3'),
    path('step1_C4/', step1_C4, name='step1_C4'),
    path('step2_C4/', step2_C4, name='step2_C4'),
    path('step3_C4/', step3_C4, name='step3_C4'),
    path('resultatsA2/', views.resultatsA2, name='resultatsA2'),
    path('resultatsA1/', views.resultatsA1, name='resultatsA1'),
    path('resultatsA3/', views.resultatsA3, name='resultatsA3'),
    path('resultatsA4/', views.resultatsA4, name='resultatsA4'),
    path('resultatsA5/', views.resultatsA5, name='resultatsA5'),
    path('resultatsA6/', views.resultatsA6, name='resultatsA6'),
    path('resultatsB1/', views.resultatsB1, name='resultatsB1'),
    path('resultatsB2/', views.resultatsB2, name='resultatsB2'),
    path('resultatsB3/', views.resultatsB3, name='resultatsB3'),
    path('resultatsB4/', views.resultatsB4, name='resultatsB4'),
    path('resultatsC1/', views.resultatsC1, name='resultatsC1'),
    path('resultatsC2/', views.resultatsC2, name='resultatsC2'),
    path('resultatsC3/', views.resultatsC3, name='resultatsC3'),
    path('resultatsC4/', views.resultatsC4, name='resultatsC4'),
    path('resultsA/', views.resultatsA, name='resultsA'),
    path('resultsB/', views.resultatsB, name='resultsB'),
    path('resultsC/', views.resultatsC, name='resultsC'),
    path('finished/', views.finished, name='finished'),
    path('finishedA1/', views.finishedA1, name='finishedA1'),
    path('finishedA2/', views.finishedA2, name='finishedA2'),
    path('finishedA3/', views.finishedA3, name='finishedA3'),
    path('finishedA4/', views.finishedA4, name='finishedA4'),
    path('finishedA5/', views.finishedA5, name='finishedA5'),
    path('finishedA6/', views.finishedA6, name='finishedA6'),
    path('finishedB1/', views.finishedB1, name='finishedB1'),
    path('finishedB2/', views.finishedB2, name='finishedB2'),
    path('finishedB3/', views.finishedB3, name='finishedB3'),
    path('finishedB4/', views.finishedB4, name='finishedB4'),
    path('finishedC1/', views.finishedC1, name='finishedC1'),
    path('finishedC2/', views.finishedC2, name='finishedC2'),
    path('finishedC3/', views.finishedC3, name='finishedC3'),
    path('finishedC4/', views.finishedC4, name='finishedC4'),
    path('resultats_all/', views.resultats_all, name='resultats_all'),
    path('contact/', views.contact, name='contact'),
    path('generateB-pdf/', generateB_pdf, name='generateB_pdf'),
    path('generateC-pdf/', generateC_pdf, name='generateC_pdf'),
    path('generateA-pdf/', generateA_pdf, name='generateA_pdf'),
    path('statistic/', views.statistic, name='statistic'),
    path('accueil/', views.accueil, name='accueil'),
    path('terms-of-use/', views.terms_of_use, name='terms_of_use'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('parcoursresultats/', views.parcoursresultats, name='parcoursresultats'),
    path('generate_All_pdf/', views.generate_All_pdf, name='generate_All_pdf'),
    path('export_to_excel/', views.export_to_excel, name='export_to_excel'),
    path('export_A_to_excel/', views.export_A_to_excel, name='export_A_to_excel'),
    path('export_B_to_excel/', views.export_B_to_excel, name='export_B_to_excel'),
    path('export_C_to_excel/', views.export_C_to_excel, name='export_C_to_excel'),

]

